### ISSUE TITLE
Message claim is not working

### ISSUE THREAD

**Issue by kiran-anand14** [kiran-anand14/async-comm#10]
_Test Case:_
 - 1 producer (A) and 2 consumers (X and Y) in the system. Have a look at the docker-compose.yaml and corresponding configuration related yaml files in the attachment.
 - Stop a consumer using docker stop command after around 1 min of launching containers using docker-compose.

_Observation:_ 
On stopping one of the consumers after around 1 min of launching containers through docker-compose, message pulled by a dying consumer for processing is not reclaimed by another consumer running in the system.

In the attachment, you will find logs for producers and consumers in app-*.log files. Check for **App-Prod-A-producerA-05:14:12:23:26.858** message in app-cons-y.log (logs of consumer Y), it was pulled by it, but while it was processing it, in background, I stopped the container running consumer Y using docker stop \<container-id\> command. This message is never reclaimed by Consumer X.

Please fix it.
[tc-3.tar.gz](https://github.com/kiran-anand14/async-comm/files/6478899/tc-3.tar.gz)

**Comment by parvez0** [comment]
Have you tried checking if any messages are on the pending list for the dying consumer?

**Comment by kiran-anand14** [comment]
I haven't checked at Redis' level, but if look at the logs for App-Prod-A-producerA-05:14:12:23:26.858, it clearly shows that message is not reclaimed. Its easily reproducible, try it at your setup.

**Comment by kiran-anand14** [comment]
Are you still working on this?

**Comment by parvez0** [comment]
Yeah It's fixed now creating a pull request

**Comment by kiran-anand14** [comment]
Its still not working, please check attached logs. Consumer Y was killed, search for **App-Prod-A-producerA-05:21:12:19:30.967** msg in **app-cons-y-app.log** log file, it was pulled, but never reclaimed and processed.

Log files also contain asyncomm/redis logs for consumers as well.

Configuration files and Docker compose files are also in the gz file.

Its very easily reproducible, please test it thoroughly before releasing the fix.
[tc-3-210521.tar.gz](https://github.com/kiran-anand14/async-comm/files/6522551/tc-3-210521.tar.gz)

**Comment by parvez0** [comment]
I ran the simulation with your docker files 3 times logs attached and it worked fine, please go through the logs and verify
T1 :- App-Prod-A-producerA-05:21:13:02:56.629, 
T2:- App-Prod-A-producerA-05:21:13:11:51.871, 
T3  :- App-Prod-A-producerA-05:21:13:12:21.620
[tc-3-verified.tar.gz](https://github.com/kiran-anand14/async-comm/files/6522733/tc-3-verified.tar.gz)

As to why your specific test didn't work I think it was because when you deleted consumer Y it was acknowledging it and it never to pending message that's why it didn't came to redis logs as well.

**Comment by kiran-anand14** [comment]
> As to why your specific test didn't work I think it was because when you deleted consumer Y it was acknowledging it and it never to pending message that's why it didn't came to redis logs as well.

I also tested it couple of times and I observed that message was not claimed. I will test it again multiple times and let you know if your theory is correct or not.

On a separate are you sure that you are not having any fix local to your code?

**Comment by parvez0** [comment]
no I created a new image of the last pull request and tested this
